name: Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:

  Scanning-Terraform-modules-in-repositories:
    uses: ./.github/workflows/codescanning.yml
    with:
      organization_name: FuturStarup
      topics: test
      terraform_dependency_validation: enabled
    secrets:
      token: ${{ secrets.token }}


  Undo-tests:
    needs: [Scanning-Terraform-modules-in-repositories]
    runs-on: ubuntu-latest
    steps:   
      - name: Undo Test Scanning Terraform modules in repositories
        env:
          GH_TOKEN: ${{ secrets.token }}
        run: |-
              gh api --method DELETE -H "Accept: application/vnd.github+json" repos/FuturStarup/dcs-karim_test_6/git/refs/heads/onecloudatomation-dependabot-autoremediation


