name: Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:

  Scanning-Terraform-modules-in-repositories:
    uses: ./.github/workflows/codescanning.yml
    with:
      organization_name: OneCloudAutomation
      topics: test-git-assurance
      terraform_dependency_validation: enabled
    secrets:
      token: ${{ secrets.token }}
