name: Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  Scanning-Terraform-modules-in-repositories:
    uses: FuturStarup/dcs-harshada-testing41/actions/workflows/codescanning.yml
    with:
      #### Required Inputs ####
      organization_name: FuturStarup
      topics: test
      terraform_dependency_validation: enabled
    secrets:
      token: ${{ secrets.token}}

