name: Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:

  Scanning-public-repositories:
    uses: ./.github/workflows/scanPublicRepository.yml
    with:
      organization_name: FuturStarup
      new_type: private
      report: true
      enforce: false
      runner_name: ubuntu-latest
    secrets: inherit
