name: Scan public repository
on:
  workflow_call:
    inputs:
      organization_name:
        description: 'Organization name'
        required: true
        default: 'OneCloudAutomation'
        type: string
      enforce:
        description: 'enforce change to defined type: internal or private'
        required: false
        default: true
        type: boolean      
      new_type:
        description: 'change public repository to ( internal / private )'
        required: false
        default: private
        type: string
      report:
        description: 'report it ( true / false )'
        required: true
        default: true
        type: boolean      
      runner_name:
        description: 'Runner name'
        default: ubuntu-latest
        type: string
    secrets:
      token:
        required: true
jobs:
  scanPublicRepositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v3

      - name: Check for github cli
        id: check-gh
        run: |
          if [[ $(gh --version >/dev/null 2>&1; echo $?) -eq 0 ]]; then
            echo "gh_exist=true" >> $GITHUB_OUTPUT
          else 
            echo "gh_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup github cli
        if: steps.check-gh.outputs.gh_exist == 'false'
        run: |
          # Install gh cli
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update && sudo apt -y install gh

      - name: login to github cli
        env:
          GITHUB_TOKEN: ${{ secrets.token }}  
        run: |
          # Authenticate with Github.com
          echo "Authenticate with Github.com"
          TOKEN_FILE=$(mktemp)  &&  echo -n ${GITHUB_TOKEN} > ${TOKEN_FILE}  &&  unset GITHUB_TOKEN
          gh auth login --with-token < ${TOKEN_FILE}  &&  gh auth setup-git

      - name: Get public repositories list
        id: list-repos
        env:
          GH_TOKEN: ${{ secrets.token }}
          ORGANIZATION_NAME: ${{ inputs.organization_name}}
        run: |
          echo "repos=$(gh search repos --owner FuturStarup --visibility=public --json name)" >> $GITHUB_OUTPUT

      - name: Scan public repositories
        env:
          GH_TOKEN: ${{ secrets.token}}
          REPOSITORIES: ${{ steps.list-repos.outputs.repos }}
          ORGANIZATION_NAME: ${{ inputs.organization_name}}
          TYPE: ${{ inputs.new_type }}
          REPORT: ${{ inputs.report }}
          ENFORCE: ${{ inputs.enforce }}
          
        run: |
          for repo in $(echo "${REPOSITORIES}" | jq -r '.[] | @base64'); do
            _jq() { echo ${repo} | base64 --decode | jq -r ${1}; }
            if [ $REPORT  = true ]
            then
              echo "Repository '$(_jq '.name')' is public, please updated its visibility to '${TYPE}'"
            fi
            
            if [ $ENFORCE = true ]
            then
                echo -n "Set '$(_jq '.name')' repository visibility to '${TYPE}'... ";
                [[ $(gh api -X PATCH repos/${ORGANIZATION_NAME}/$(_jq '.name') -f visibility=${TYPE} | jq ".visibility")  = \"${TYPE}\" ]] \
                  && echo "ok" || (
                    echo "failed";
                    exit 1
                )
            fi
          done
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

